### ISSUE TITLE
Low fidelity wireframe maken voor zoekbalk

### ISSUE THREAD

**Issue by Stijnwingens** [han-i28/I-Project#61]
Geplande tijd: 1hr

Maak een layout voor de zoekbalk. Denk na over zoeksuggesties, andere functies die eventueel zouden kunnen samenwerken met de zoekbalk, en waar de resultaten zouden moeten komen.... Zoeken werkt voor voorwerpen, rubrieken, subrubrieken, enz... Denk na over wat binnen de zoekfunctie valt, en wat hierbuiten. Leg dit eventueel kort vast in een document. (4-8 regels zou voldoende moeten zijn)

**Comment by jasperjacobs** [comment]
done en review gedaan by michel
