### ISSUE TITLE
Low fidelity wireframe maken voor prijsfilter

### ISSUE THREAD

**Issue by Stijnwingens** [han-i28/I-Project#62]
Geplande tijd: 1u

Maak een wireframe van de layout van de filterfunctie. Denk na over (genoeg) ruimte voor andere filterfuncties. Je hoeft niet te bedenken hoe deze andere filters eruit moeten gaan zien, of hoe groot ze worden, maar probeer rekening te houden met andere filters in jouw idee voor de prijsfilter. Komt de prijsfilter bovenaan? onderaan? halverwege?

Laat je gekozen filters nog op een bepaalde manier zien in het scherm buiten de checkboxen om? Of juist niet? Waarom kies je daarvoor? leg dit vast in een documentje. (6-8 regels is voldoende)

**Comment by MichelBodde** [comment]
Zie wireframes.bmpr op de drive(sprint 1 map)
